# ─────────────────────────────────────────────────────────────────────────────
# Escala Digital Ventures — Dockerfile
# SPEC-P6 AC-1 · Next.js standalone output, multi-stage, non-root
#
# Stage 1 (deps):    install production + dev dependencies
# Stage 2 (builder): build the Next.js standalone bundle
# Stage 3 (runner):  minimal runtime image — only the standalone output
#
# Build args (all optional — defaults are safe for local testing):
#   NEXT_PUBLIC_SITE_URL  e.g. https://escaladigitalventures.com
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1: dependency install ───────────────────────────────────────────────
FROM node:22-slim AS deps

WORKDIR /app

# Copy manifests only — layer-cache friendly
COPY package.json package-lock.json ./

# Install all deps (dev included — needed for the build step)
# Using npm install instead of npm ci: local dev uses Node v25 which generates
# a lockfile with entries (e.g. @emnapi) that Node v22 npm ci rejects.
# npm install is safe here because the image is built from a clean context.
RUN npm install --ignore-scripts

# ── Stage 2: build ────────────────────────────────────────────────────────────
FROM node:22-slim AS builder

WORKDIR /app

# Build-time public env vars (injected by CI; safe to bake into the image)
ARG NEXT_PUBLIC_SITE_URL=https://escaladigitalventures.com
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL

# Copy deps from stage 1
COPY --from=deps /app/node_modules ./node_modules

# Copy source
COPY . .

# Ensure public/ exists (Next.js standalone requires it even if empty)
RUN mkdir -p ./public

# Build — produces .next/standalone + .next/static
RUN npm run build

# ── Stage 3: minimal runtime ──────────────────────────────────────────────────
FROM node:22-slim AS runner

WORKDIR /app

# Security: run as non-root
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy only what the standalone server needs
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static    ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public          ./public

USER nextjs

# Cloud Run injects PORT; Next.js standalone server reads it automatically
ENV PORT=8080
ENV HOSTNAME=0.0.0.0
# NODE_ENV is set at runtime via Cloud Run env vars / Secret Manager
ENV NODE_ENV=production

EXPOSE 8080

# Standalone entry point generated by Next.js
CMD ["node", "server.js"]
